### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PanjaTuig** [Elkropac/hassio-intex-spa#1]
Logger: homeassistant.setup
Source: setup.py:298
First occurred: 09:49:23 (1 occurrences)
Last logged: 09:49:23

Unable to prepare setup for platform intex_spa.switch: Platform not found (No module named 'custom_components.intex_spa.switch').

**Comment by Elkropac** [comment]
Hi,
the whole thing is not working, i'm just trying to figure out how to bash it together

**Comment by PanjaTuig** [comment]
i have it working on node red, so what you need to fix it?

**Comment by Elkropac** [comment]
Sorry, I don't have access to yours nodered.

I want to learn how to make hass intergration and this should do it

**Comment by KubaDavid** [comment]
Hey guys, just received the same error. @PanjaTuig How did you manage to solve that? 

Každopádně super práce!

**Comment by Elkropac** [comment]
> Hey guys, just received the same error. @PanjaTuig How did you manage to solve that?
> 
> Každopádně super práce!

It does not work at all. I used this repo to save my work from fall and i hoped to work on it during winter, which did not happen.

@PanjaTuig maybe uses https://github.com/claudiospizzi/node-red-contrib-intexspa , but it works over cloud, i think. I'm targeting on local control, using data i managed to capture on my local network

**Comment by PanjaTuig** [comment]
> > Hey guys, just received the same error. @PanjaTuig How did you manage to solve that?
> > Každopádně super práce!
> 
> It does not work at all. I used this repo to save my work from fall and i hoped to work on it during winter, which did not happen.
> 
> @PanjaTuig maybe uses https://github.com/claudiospizzi/node-red-contrib-intexspa , but it works over cloud, i think. I'm targeting on local control, using data i managed to capture on my local network

@Elkropac true i get that one from node red and it is cloud pulled. i want also get it local..

**Comment by Elkropac** [comment]
There is proper integration now https://github.com/mathieu-mp/homeassistant-intex-spa . It will be ready for use soon

**Comment by FrankSchoene** [comment]
Cool. Looking forward to have this working. Thanks for your work.

Am 20. Juni 2022 08:11:05 MESZ schrieb Elkropac ***@***.***>:
>There is proper integration now https://github.com/mathieu-mp/homeassistant-intex-spa . It will be ready for use soon
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Elkropac/hassio-intex-spa/issues/1#issuecomment-1160014585
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
